version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '8000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: binance_db
    volumes:
      - ./data:/var/lib/postgresql/data
